version: '3'
services: 
  strapi_server:
    image: poomport/app:1.0.0
    container_name: 67-ced-strapi
    restart: unless-stopped
    ports:
      - 8080:1337 
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: false
    env_file: 
      - .env
  db:
    container_name: 67-ced-db
    image: postgres:15-bullseye
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}